# Generated by Django 4.0.7 on 2023-03-13 05:18

import buzzfeed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadRoute', models.CharField(max_length=450)),
                ('loadDate', models.DateTimeField(auto_now_add=True)),
                ('loadImage', models.ImageField(blank=True, upload_to=buzzfeed.models.get_img_sighting)),
            ],
        ),
    ]
